// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvinAx72Felxbw_Zq5g6gMCJGuh7zzvZQ',
    appId: '1:497629835372:web:b234da7c0fc03f54e06849',
    messagingSenderId: '497629835372',
    projectId: 'ludo-master-1cfac',
    authDomain: 'ludo-master-1cfac.firebaseapp.com',
    storageBucket: 'ludo-master-1cfac.firebasestorage.app',
    measurementId: 'G-J3ZS35R8Y1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiCkz7eCclFT6B9JvypRsT44eC7wTqbl8',
    appId: '1:497629835372:android:63acaa789b067a4ee06849',
    messagingSenderId: '497629835372',
    projectId: 'ludo-master-1cfac',
    storageBucket: 'ludo-master-1cfac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56J52od6mk_tjvDkch4EAQ9bkp3P9QM4',
    appId: '1:497629835372:ios:f9cccd1a32946fbce06849',
    messagingSenderId: '497629835372',
    projectId: 'ludo-master-1cfac',
    storageBucket: 'ludo-master-1cfac.firebasestorage.app',
    androidClientId: '497629835372-dur0imqadkrpisdeaf84bfpatb46s2l6.apps.googleusercontent.com',
    iosClientId: '497629835372-n46tkrlpkruqd3n4hcsjp916i2fkejq2.apps.googleusercontent.com',
    iosBundleId: 'com.ludomaster.app.ludoMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA56J52od6mk_tjvDkch4EAQ9bkp3P9QM4',
    appId: '1:497629835372:ios:f9cccd1a32946fbce06849',
    messagingSenderId: '497629835372',
    projectId: 'ludo-master-1cfac',
    storageBucket: 'ludo-master-1cfac.firebasestorage.app',
    androidClientId: '497629835372-dur0imqadkrpisdeaf84bfpatb46s2l6.apps.googleusercontent.com',
    iosClientId: '497629835372-n46tkrlpkruqd3n4hcsjp916i2fkejq2.apps.googleusercontent.com',
    iosBundleId: 'com.ludomaster.app.ludoMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvinAx72Felxbw_Zq5g6gMCJGuh7zzvZQ',
    appId: '1:497629835372:web:e94907b984edf080e06849',
    messagingSenderId: '497629835372',
    projectId: 'ludo-master-1cfac',
    authDomain: 'ludo-master-1cfac.firebaseapp.com',
    storageBucket: 'ludo-master-1cfac.firebasestorage.app',
    measurementId: 'G-8JNT7FNVK4',
  );
}
